# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-28 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_Study_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tims_schema', models.CharField(max_length=60)),
                ('schema_name', models.CharField(max_length=60)),
                ('is_study_enabled', models.BooleanField(default=True)),
                ('study_partition', models.IntegerField(blank=True)),
            ],
        ),
    ]
