# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-29 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miodsapi', '0003_auto_20200629_1220'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meta_study_config',
            table=None,
        ),
    ]
